# Generated by Django 5.2.7 on 2025-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
