# Generated by Django 5.2.7 on 2025-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phon_number', models.IntegerField()),
                ('birthday', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
