# Generated by Django 5.2.7 on 2025-10-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/photo_2025-06-10_23-20-04.jpg', upload_to='blog/'),
        ),
    ]
