# Generated by Django 5.2.7 on 2025-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_re',
            field=models.BooleanField(default=False),
        ),
    ]
